# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui_game.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_main_win(object):
    def setupUi(self, main_win):
        main_win.setObjectName("main_win")
        main_win.resize(1024, 768)
        main_win.setMinimumSize(QtCore.QSize(1024, 768))
        main_win.setSizeIncrement(QtCore.QSize(1024, 768))
        self.centralwidget = QtWidgets.QWidget(main_win)
        self.centralwidget.setMinimumSize(QtCore.QSize(1024, 768))
        self.centralwidget.setStyleSheet("")
        self.centralwidget.setObjectName("centralwidget")
        self.popup_set_status = QtWidgets.QFrame(self.centralwidget)
        self.popup_set_status.setGeometry(QtCore.QRect(0, 0, 1024, 768))
        self.popup_set_status.setStyleSheet("")
        self.popup_set_status.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.popup_set_status.setFrameShadow(QtWidgets.QFrame.Raised)
        self.popup_set_status.setObjectName("popup_set_status")
        self.frame_set = QtWidgets.QFrame(self.popup_set_status)
        self.frame_set.setGeometry(QtCore.QRect(240, 260, 541, 161))
        self.frame_set.setStyleSheet("background-color: rgba(0, 0, 0, 150);")
        self.frame_set.setFrameShape(QtWidgets.QFrame.Box)
        self.frame_set.setFrameShadow(QtWidgets.QFrame.Plain)
        self.frame_set.setLineWidth(2)
        self.frame_set.setObjectName("frame_set")
        self.text_info_set = QtWidgets.QLabel(self.frame_set)
        self.text_info_set.setGeometry(QtCore.QRect(160, 0, 221, 81))
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.text_info_set.setFont(font)
        self.text_info_set.setAutoFillBackground(False)
        self.text_info_set.setStyleSheet("color: rgb(255, 255, 255);\n"
"background-color: rgba(255, 255, 255, 0);")
        self.text_info_set.setAlignment(QtCore.Qt.AlignCenter)
        self.text_info_set.setObjectName("text_info_set")
        self.btn_ok_set = QtWidgets.QPushButton(self.frame_set)
        self.btn_ok_set.setGeometry(QtCore.QRect(200, 100, 141, 41))
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.btn_ok_set.setFont(font)
        self.btn_ok_set.setAutoFillBackground(False)
        self.btn_ok_set.setStyleSheet("color: rgb(255, 255, 255);")
        self.btn_ok_set.setDefault(True)
        self.btn_ok_set.setFlat(True)
        self.btn_ok_set.setObjectName("btn_ok_set")
        self.popup_match_status = QtWidgets.QFrame(self.centralwidget)
        self.popup_match_status.setGeometry(QtCore.QRect(0, 0, 1024, 768))
        self.popup_match_status.setStyleSheet("")
        self.popup_match_status.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.popup_match_status.setFrameShadow(QtWidgets.QFrame.Raised)
        self.popup_match_status.setObjectName("popup_match_status")
        self.frame_match = QtWidgets.QFrame(self.popup_match_status)
        self.frame_match.setGeometry(QtCore.QRect(240, 260, 541, 161))
        self.frame_match.setStyleSheet("background-color: rgba(0, 0, 0, 150);")
        self.frame_match.setFrameShape(QtWidgets.QFrame.Box)
        self.frame_match.setFrameShadow(QtWidgets.QFrame.Plain)
        self.frame_match.setLineWidth(2)
        self.frame_match.setObjectName("frame_match")
        self.text_info_match = QtWidgets.QLabel(self.frame_match)
        self.text_info_match.setGeometry(QtCore.QRect(160, 0, 221, 81))
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.text_info_match.setFont(font)
        self.text_info_match.setAutoFillBackground(False)
        self.text_info_match.setStyleSheet("color: rgb(255, 255, 255);\n"
"background-color: rgba(255, 255, 255, 0);")
        self.text_info_match.setAlignment(QtCore.Qt.AlignCenter)
        self.text_info_match.setObjectName("text_info_match")
        self.btn_ok_match = QtWidgets.QPushButton(self.frame_match)
        self.btn_ok_match.setGeometry(QtCore.QRect(200, 100, 141, 41))
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.btn_ok_match.setFont(font)
        self.btn_ok_match.setAutoFillBackground(False)
        self.btn_ok_match.setStyleSheet("color: rgb(255, 255, 255);")
        self.btn_ok_match.setDefault(True)
        self.btn_ok_match.setFlat(True)
        self.btn_ok_match.setObjectName("btn_ok_match")
        self.stacked_widget = QtWidgets.QStackedWidget(self.centralwidget)
        self.stacked_widget.setEnabled(True)
        self.stacked_widget.setGeometry(QtCore.QRect(0, 0, 1024, 768))
        self.stacked_widget.setMinimumSize(QtCore.QSize(1024, 768))
        self.stacked_widget.setMaximumSize(QtCore.QSize(1024, 768))
        self.stacked_widget.setStyleSheet("background-color: rgb(205, 218, 248);")
        self.stacked_widget.setFrameShadow(QtWidgets.QFrame.Plain)
        self.stacked_widget.setObjectName("stacked_widget")
        self.main_screen = QtWidgets.QWidget()
        self.main_screen.setObjectName("main_screen")
        self.name_pazaak = QtWidgets.QLabel(self.main_screen)
        self.name_pazaak.setGeometry(QtCore.QRect(412, 30, 200, 81))
        font = QtGui.QFont()
        font.setPointSize(24)
        self.name_pazaak.setFont(font)
        self.name_pazaak.setAlignment(QtCore.Qt.AlignCenter)
        self.name_pazaak.setObjectName("name_pazaak")
        self.btn_play = QtWidgets.QPushButton(self.main_screen)
        self.btn_play.setGeometry(QtCore.QRect(412, 210, 200, 71))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.btn_play.setFont(font)
        self.btn_play.setObjectName("btn_play")
        self.btn_help = QtWidgets.QPushButton(self.main_screen)
        self.btn_help.setGeometry(QtCore.QRect(412, 310, 200, 71))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.btn_help.setFont(font)
        self.btn_help.setObjectName("btn_help")
        self.btn_quit_game = QtWidgets.QPushButton(self.main_screen)
        self.btn_quit_game.setGeometry(QtCore.QRect(412, 410, 200, 71))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.btn_quit_game.setFont(font)
        self.btn_quit_game.setObjectName("btn_quit_game")
        self.stacked_widget.addWidget(self.main_screen)
        self.help_screen = QtWidgets.QWidget()
        self.help_screen.setObjectName("help_screen")
        self.btn_help_to_main = QtWidgets.QPushButton(self.help_screen)
        self.btn_help_to_main.setGeometry(QtCore.QRect(30, 20, 161, 41))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.btn_help_to_main.setFont(font)
        self.btn_help_to_main.setObjectName("btn_help_to_main")
        self.label = QtWidgets.QLabel(self.help_screen)
        self.label.setGeometry(QtCore.QRect(330, 170, 351, 311))
        font = QtGui.QFont()
        font.setPointSize(24)
        self.label.setFont(font)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setWordWrap(True)
        self.label.setObjectName("label")
        self.stacked_widget.addWidget(self.help_screen)
        self.deck_screen = QtWidgets.QWidget()
        self.deck_screen.setObjectName("deck_screen")
        self.btn_start_match = QtWidgets.QPushButton(self.deck_screen)
        self.btn_start_match.setEnabled(False)
        self.btn_start_match.setGeometry(QtCore.QRect(830, 20, 161, 41))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.btn_start_match.setFont(font)
        self.btn_start_match.setObjectName("btn_start_match")
        self.btn_deck_to_main = QtWidgets.QPushButton(self.deck_screen)
        self.btn_deck_to_main.setGeometry(QtCore.QRect(30, 20, 161, 41))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.btn_deck_to_main.setFont(font)
        self.btn_deck_to_main.setObjectName("btn_deck_to_main")
        self.btn_card_plus_1 = QtWidgets.QPushButton(self.deck_screen)
        self.btn_card_plus_1.setEnabled(True)
        self.btn_card_plus_1.setGeometry(QtCore.QRect(220, 90, 82, 112))
        self.btn_card_plus_1.setStyleSheet("QPushButton:hover {\n"
"    border: 2px solid red;\n"
"    border-radius: 8px;\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    border: none;\n"
"}")
        self.btn_card_plus_1.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("assets/card_plus_1.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btn_card_plus_1.setIcon(icon)
        self.btn_card_plus_1.setIconSize(QtCore.QSize(80, 110))
        self.btn_card_plus_1.setFlat(True)
        self.btn_card_plus_1.setObjectName("btn_card_plus_1")
        self.btn_card_plus_2 = QtWidgets.QPushButton(self.deck_screen)
        self.btn_card_plus_2.setEnabled(True)
        self.btn_card_plus_2.setGeometry(QtCore.QRect(320, 90, 82, 112))
        self.btn_card_plus_2.setStyleSheet("QPushButton:hover {\n"
"    border: 2px solid red;\n"
"    border-radius: 8px;\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    border: none;\n"
"}")
        self.btn_card_plus_2.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("assets/card_plus_2.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btn_card_plus_2.setIcon(icon1)
        self.btn_card_plus_2.setIconSize(QtCore.QSize(80, 110))
        self.btn_card_plus_2.setFlat(True)
        self.btn_card_plus_2.setObjectName("btn_card_plus_2")
        self.btn_card_plus_3 = QtWidgets.QPushButton(self.deck_screen)
        self.btn_card_plus_3.setEnabled(True)
        self.btn_card_plus_3.setGeometry(QtCore.QRect(420, 90, 82, 112))
        self.btn_card_plus_3.setStyleSheet("QPushButton:hover {\n"
"    border: 2px solid red;\n"
"    border-radius: 8px;\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    border: none;\n"
"}")
        self.btn_card_plus_3.setText("")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap("assets/card_plus_3.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btn_card_plus_3.setIcon(icon2)
        self.btn_card_plus_3.setIconSize(QtCore.QSize(80, 110))
        self.btn_card_plus_3.setFlat(True)
        self.btn_card_plus_3.setObjectName("btn_card_plus_3")
        self.btn_card_plus_4 = QtWidgets.QPushButton(self.deck_screen)
        self.btn_card_plus_4.setEnabled(True)
        self.btn_card_plus_4.setGeometry(QtCore.QRect(520, 90, 82, 112))
        self.btn_card_plus_4.setStyleSheet("QPushButton:hover {\n"
"    border: 2px solid red;\n"
"    border-radius: 8px;\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    border: none;\n"
"}")
        self.btn_card_plus_4.setText("")
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap("assets/card_plus_4.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btn_card_plus_4.setIcon(icon3)
        self.btn_card_plus_4.setIconSize(QtCore.QSize(80, 110))
        self.btn_card_plus_4.setFlat(True)
        self.btn_card_plus_4.setObjectName("btn_card_plus_4")
        self.btn_card_plus_5 = QtWidgets.QPushButton(self.deck_screen)
        self.btn_card_plus_5.setEnabled(True)
        self.btn_card_plus_5.setGeometry(QtCore.QRect(620, 90, 82, 112))
        self.btn_card_plus_5.setStyleSheet("QPushButton:hover {\n"
"    border: 2px solid red;\n"
"    border-radius: 8px;\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    border: none;\n"
"}")
        self.btn_card_plus_5.setText("")
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap("assets/card_plus_5.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btn_card_plus_5.setIcon(icon4)
        self.btn_card_plus_5.setIconSize(QtCore.QSize(80, 110))
        self.btn_card_plus_5.setFlat(True)
        self.btn_card_plus_5.setObjectName("btn_card_plus_5")
        self.btn_card_plus_6 = QtWidgets.QPushButton(self.deck_screen)
        self.btn_card_plus_6.setEnabled(True)
        self.btn_card_plus_6.setGeometry(QtCore.QRect(720, 90, 82, 112))
        self.btn_card_plus_6.setStyleSheet("QPushButton:hover {\n"
"    border: 2px solid red;\n"
"    border-radius: 8px;\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    border: none;\n"
"}")
        self.btn_card_plus_6.setText("")
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap("assets/card_plus_6.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btn_card_plus_6.setIcon(icon5)
        self.btn_card_plus_6.setIconSize(QtCore.QSize(80, 110))
        self.btn_card_plus_6.setFlat(True)
        self.btn_card_plus_6.setObjectName("btn_card_plus_6")
        self.btn_card_minus_1 = QtWidgets.QPushButton(self.deck_screen)
        self.btn_card_minus_1.setEnabled(True)
        self.btn_card_minus_1.setGeometry(QtCore.QRect(220, 210, 82, 112))
        self.btn_card_minus_1.setStyleSheet("QPushButton:hover {\n"
"    border: 2px solid red;\n"
"    border-radius: 8px;\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    border: none;\n"
"}")
        self.btn_card_minus_1.setText("")
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap("assets/card_minus_1.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btn_card_minus_1.setIcon(icon6)
        self.btn_card_minus_1.setIconSize(QtCore.QSize(80, 110))
        self.btn_card_minus_1.setFlat(True)
        self.btn_card_minus_1.setObjectName("btn_card_minus_1")
        self.btn_card_minus_2 = QtWidgets.QPushButton(self.deck_screen)
        self.btn_card_minus_2.setEnabled(True)
        self.btn_card_minus_2.setGeometry(QtCore.QRect(320, 210, 82, 112))
        self.btn_card_minus_2.setStyleSheet("QPushButton:hover {\n"
"    border: 2px solid red;\n"
"    border-radius: 8px;\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    border: none;\n"
"}")
        self.btn_card_minus_2.setText("")
        icon7 = QtGui.QIcon()
        icon7.addPixmap(QtGui.QPixmap("assets/card_minus_2.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btn_card_minus_2.setIcon(icon7)
        self.btn_card_minus_2.setIconSize(QtCore.QSize(80, 110))
        self.btn_card_minus_2.setFlat(True)
        self.btn_card_minus_2.setObjectName("btn_card_minus_2")
        self.btn_card_minus_3 = QtWidgets.QPushButton(self.deck_screen)
        self.btn_card_minus_3.setEnabled(True)
        self.btn_card_minus_3.setGeometry(QtCore.QRect(420, 210, 82, 112))
        self.btn_card_minus_3.setStyleSheet("QPushButton:hover {\n"
"    border: 2px solid red;\n"
"    border-radius: 8px;\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    border: none;\n"
"}")
        self.btn_card_minus_3.setText("")
        icon8 = QtGui.QIcon()
        icon8.addPixmap(QtGui.QPixmap("assets/card_minus_3.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btn_card_minus_3.setIcon(icon8)
        self.btn_card_minus_3.setIconSize(QtCore.QSize(80, 110))
        self.btn_card_minus_3.setFlat(True)
        self.btn_card_minus_3.setObjectName("btn_card_minus_3")
        self.btn_card_minus_4 = QtWidgets.QPushButton(self.deck_screen)
        self.btn_card_minus_4.setEnabled(True)
        self.btn_card_minus_4.setGeometry(QtCore.QRect(520, 210, 82, 112))
        self.btn_card_minus_4.setStyleSheet("QPushButton:hover {\n"
"    border: 2px solid red;\n"
"    border-radius: 8px;\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    border: none;\n"
"}")
        self.btn_card_minus_4.setText("")
        icon9 = QtGui.QIcon()
        icon9.addPixmap(QtGui.QPixmap("assets/card_minus_4.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btn_card_minus_4.setIcon(icon9)
        self.btn_card_minus_4.setIconSize(QtCore.QSize(80, 110))
        self.btn_card_minus_4.setFlat(True)
        self.btn_card_minus_4.setObjectName("btn_card_minus_4")
        self.btn_card_minus_5 = QtWidgets.QPushButton(self.deck_screen)
        self.btn_card_minus_5.setEnabled(True)
        self.btn_card_minus_5.setGeometry(QtCore.QRect(620, 210, 82, 112))
        self.btn_card_minus_5.setStyleSheet("QPushButton:hover {\n"
"    border: 2px solid red;\n"
"    border-radius: 8px;\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    border: none;\n"
"}")
        self.btn_card_minus_5.setText("")
        icon10 = QtGui.QIcon()
        icon10.addPixmap(QtGui.QPixmap("assets/card_minus_5.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btn_card_minus_5.setIcon(icon10)
        self.btn_card_minus_5.setIconSize(QtCore.QSize(80, 110))
        self.btn_card_minus_5.setFlat(True)
        self.btn_card_minus_5.setObjectName("btn_card_minus_5")
        self.btn_card_minus_6 = QtWidgets.QPushButton(self.deck_screen)
        self.btn_card_minus_6.setEnabled(True)
        self.btn_card_minus_6.setGeometry(QtCore.QRect(720, 210, 82, 112))
        self.btn_card_minus_6.setStyleSheet("QPushButton:hover {\n"
"    border: 2px solid red;\n"
"    border-radius: 8px;\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    border: none;\n"
"}")
        self.btn_card_minus_6.setText("")
        icon11 = QtGui.QIcon()
        icon11.addPixmap(QtGui.QPixmap("assets/card_minus_6.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btn_card_minus_6.setIcon(icon11)
        self.btn_card_minus_6.setIconSize(QtCore.QSize(80, 110))
        self.btn_card_minus_6.setFlat(True)
        self.btn_card_minus_6.setObjectName("btn_card_minus_6")
        self.btn_card_dual_1 = QtWidgets.QPushButton(self.deck_screen)
        self.btn_card_dual_1.setEnabled(True)
        self.btn_card_dual_1.setGeometry(QtCore.QRect(220, 330, 82, 112))
        self.btn_card_dual_1.setStyleSheet("QPushButton:hover {\n"
"    border: 2px solid red;\n"
"    border-radius: 8px;\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    border: none;\n"
"}")
        self.btn_card_dual_1.setText("")
        icon12 = QtGui.QIcon()
        icon12.addPixmap(QtGui.QPixmap("assets/card_dual_1.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btn_card_dual_1.setIcon(icon12)
        self.btn_card_dual_1.setIconSize(QtCore.QSize(80, 110))
        self.btn_card_dual_1.setFlat(True)
        self.btn_card_dual_1.setObjectName("btn_card_dual_1")
        self.btn_card_dual_2 = QtWidgets.QPushButton(self.deck_screen)
        self.btn_card_dual_2.setEnabled(True)
        self.btn_card_dual_2.setGeometry(QtCore.QRect(320, 330, 82, 112))
        self.btn_card_dual_2.setStyleSheet("QPushButton:hover {\n"
"    border: 2px solid red;\n"
"    border-radius: 8px;\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    border: none;\n"
"}")
        self.btn_card_dual_2.setText("")
        icon13 = QtGui.QIcon()
        icon13.addPixmap(QtGui.QPixmap("assets/card_dual_2.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btn_card_dual_2.setIcon(icon13)
        self.btn_card_dual_2.setIconSize(QtCore.QSize(80, 110))
        self.btn_card_dual_2.setFlat(True)
        self.btn_card_dual_2.setObjectName("btn_card_dual_2")
        self.btn_card_dual_3 = QtWidgets.QPushButton(self.deck_screen)
        self.btn_card_dual_3.setEnabled(True)
        self.btn_card_dual_3.setGeometry(QtCore.QRect(420, 330, 82, 112))
        self.btn_card_dual_3.setStyleSheet("QPushButton:hover {\n"
"    border: 2px solid red;\n"
"    border-radius: 8px;\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    border: none;\n"
"}")
        self.btn_card_dual_3.setText("")
        icon14 = QtGui.QIcon()
        icon14.addPixmap(QtGui.QPixmap("assets/card_dual_3.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btn_card_dual_3.setIcon(icon14)
        self.btn_card_dual_3.setIconSize(QtCore.QSize(80, 110))
        self.btn_card_dual_3.setFlat(True)
        self.btn_card_dual_3.setObjectName("btn_card_dual_3")
        self.btn_card_dual_4 = QtWidgets.QPushButton(self.deck_screen)
        self.btn_card_dual_4.setEnabled(True)
        self.btn_card_dual_4.setGeometry(QtCore.QRect(520, 330, 82, 112))
        self.btn_card_dual_4.setStyleSheet("QPushButton:hover {\n"
"    border: 2px solid red;\n"
"    border-radius: 8px;\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    border: none;\n"
"}")
        self.btn_card_dual_4.setText("")
        icon15 = QtGui.QIcon()
        icon15.addPixmap(QtGui.QPixmap("assets/card_dual_4.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btn_card_dual_4.setIcon(icon15)
        self.btn_card_dual_4.setIconSize(QtCore.QSize(80, 110))
        self.btn_card_dual_4.setFlat(True)
        self.btn_card_dual_4.setObjectName("btn_card_dual_4")
        self.btn_card_dual_5 = QtWidgets.QPushButton(self.deck_screen)
        self.btn_card_dual_5.setEnabled(True)
        self.btn_card_dual_5.setGeometry(QtCore.QRect(620, 330, 82, 112))
        self.btn_card_dual_5.setStyleSheet("QPushButton:hover {\n"
"    border: 2px solid red;\n"
"    border-radius: 8px;\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    border: none;\n"
"}")
        self.btn_card_dual_5.setText("")
        icon16 = QtGui.QIcon()
        icon16.addPixmap(QtGui.QPixmap("assets/card_dual_5.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btn_card_dual_5.setIcon(icon16)
        self.btn_card_dual_5.setIconSize(QtCore.QSize(80, 110))
        self.btn_card_dual_5.setFlat(True)
        self.btn_card_dual_5.setObjectName("btn_card_dual_5")
        self.btn_card_dual_6 = QtWidgets.QPushButton(self.deck_screen)
        self.btn_card_dual_6.setEnabled(True)
        self.btn_card_dual_6.setGeometry(QtCore.QRect(720, 330, 82, 112))
        self.btn_card_dual_6.setStyleSheet("QPushButton:hover {\n"
"    border: 2px solid red;\n"
"    border-radius: 8px;\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    border: none;\n"
"}")
        self.btn_card_dual_6.setText("")
        icon17 = QtGui.QIcon()
        icon17.addPixmap(QtGui.QPixmap("assets/card_dual_6.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btn_card_dual_6.setIcon(icon17)
        self.btn_card_dual_6.setIconSize(QtCore.QSize(80, 110))
        self.btn_card_dual_6.setFlat(True)
        self.btn_card_dual_6.setObjectName("btn_card_dual_6")
        self.btn_randomize = QtWidgets.QPushButton(self.deck_screen)
        self.btn_randomize.setGeometry(QtCore.QRect(50, 700, 161, 41))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.btn_randomize.setFont(font)
        self.btn_randomize.setObjectName("btn_randomize")
        self.btn_clear = QtWidgets.QPushButton(self.deck_screen)
        self.btn_clear.setGeometry(QtCore.QRect(50, 630, 161, 41))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.btn_clear.setFont(font)
        self.btn_clear.setObjectName("btn_clear")
        self.deck_screen_bg = QtWidgets.QLabel(self.deck_screen)
        self.deck_screen_bg.setGeometry(QtCore.QRect(0, 0, 1024, 768))
        self.deck_screen_bg.setText("")
        self.deck_screen_bg.setPixmap(QtGui.QPixmap("assets/bg_deck_screen.png"))
        self.deck_screen_bg.setObjectName("deck_screen_bg")
        self.btn_chosen_1 = QtWidgets.QPushButton(self.deck_screen)
        self.btn_chosen_1.setEnabled(False)
        self.btn_chosen_1.setGeometry(QtCore.QRect(270, 510, 82, 112))
        self.btn_chosen_1.setStyleSheet("QPushButton:hover {\n"
"    border: 2px solid red;\n"
"    border-radius: 8px;\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    border: none;\n"
"}")
        self.btn_chosen_1.setText("")
        self.btn_chosen_1.setIconSize(QtCore.QSize(80, 110))
        self.btn_chosen_1.setFlat(True)
        self.btn_chosen_1.setObjectName("btn_chosen_1")
        self.btn_chosen_2 = QtWidgets.QPushButton(self.deck_screen)
        self.btn_chosen_2.setEnabled(False)
        self.btn_chosen_2.setGeometry(QtCore.QRect(370, 510, 82, 112))
        self.btn_chosen_2.setStyleSheet("QPushButton:hover {\n"
"    border: 2px solid red;\n"
"    border-radius: 8px;\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    border: none;\n"
"}")
        self.btn_chosen_2.setText("")
        self.btn_chosen_2.setIconSize(QtCore.QSize(80, 110))
        self.btn_chosen_2.setFlat(True)
        self.btn_chosen_2.setObjectName("btn_chosen_2")
        self.btn_chosen_3 = QtWidgets.QPushButton(self.deck_screen)
        self.btn_chosen_3.setEnabled(False)
        self.btn_chosen_3.setGeometry(QtCore.QRect(470, 510, 82, 112))
        self.btn_chosen_3.setStyleSheet("QPushButton:hover {\n"
"    border: 2px solid red;\n"
"    border-radius: 8px;\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    border: none;\n"
"}")
        self.btn_chosen_3.setText("")
        self.btn_chosen_3.setIconSize(QtCore.QSize(80, 110))
        self.btn_chosen_3.setFlat(True)
        self.btn_chosen_3.setObjectName("btn_chosen_3")
        self.btn_chosen_4 = QtWidgets.QPushButton(self.deck_screen)
        self.btn_chosen_4.setEnabled(False)
        self.btn_chosen_4.setGeometry(QtCore.QRect(570, 510, 82, 112))
        self.btn_chosen_4.setStyleSheet("QPushButton:hover {\n"
"    border: 2px solid red;\n"
"    border-radius: 8px;\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    border: none;\n"
"}")
        self.btn_chosen_4.setText("")
        self.btn_chosen_4.setIconSize(QtCore.QSize(80, 110))
        self.btn_chosen_4.setFlat(True)
        self.btn_chosen_4.setObjectName("btn_chosen_4")
        self.btn_chosen_5 = QtWidgets.QPushButton(self.deck_screen)
        self.btn_chosen_5.setEnabled(False)
        self.btn_chosen_5.setGeometry(QtCore.QRect(670, 510, 82, 112))
        self.btn_chosen_5.setStyleSheet("QPushButton:hover {\n"
"    border: 2px solid red;\n"
"    border-radius: 8px;\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    border: none;\n"
"}")
        self.btn_chosen_5.setText("")
        self.btn_chosen_5.setIconSize(QtCore.QSize(80, 110))
        self.btn_chosen_5.setFlat(True)
        self.btn_chosen_5.setObjectName("btn_chosen_5")
        self.btn_chosen_6 = QtWidgets.QPushButton(self.deck_screen)
        self.btn_chosen_6.setEnabled(False)
        self.btn_chosen_6.setGeometry(QtCore.QRect(270, 630, 82, 112))
        self.btn_chosen_6.setStyleSheet("QPushButton:hover {\n"
"    border: 2px solid red;\n"
"    border-radius: 8px;\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    border: none;\n"
"}")
        self.btn_chosen_6.setText("")
        self.btn_chosen_6.setIconSize(QtCore.QSize(80, 110))
        self.btn_chosen_6.setFlat(True)
        self.btn_chosen_6.setObjectName("btn_chosen_6")
        self.btn_chosen_7 = QtWidgets.QPushButton(self.deck_screen)
        self.btn_chosen_7.setEnabled(False)
        self.btn_chosen_7.setGeometry(QtCore.QRect(370, 630, 82, 112))
        self.btn_chosen_7.setStyleSheet("QPushButton:hover {\n"
"    border: 2px solid red;\n"
"    border-radius: 8px;\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    border: none;\n"
"}")
        self.btn_chosen_7.setText("")
        self.btn_chosen_7.setIconSize(QtCore.QSize(80, 110))
        self.btn_chosen_7.setFlat(True)
        self.btn_chosen_7.setObjectName("btn_chosen_7")
        self.btn_chosen_8 = QtWidgets.QPushButton(self.deck_screen)
        self.btn_chosen_8.setEnabled(False)
        self.btn_chosen_8.setGeometry(QtCore.QRect(470, 630, 82, 112))
        self.btn_chosen_8.setStyleSheet("QPushButton:hover {\n"
"    border: 2px solid red;\n"
"    border-radius: 8px;\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    border: none;\n"
"}")
        self.btn_chosen_8.setText("")
        self.btn_chosen_8.setIconSize(QtCore.QSize(80, 110))
        self.btn_chosen_8.setFlat(True)
        self.btn_chosen_8.setObjectName("btn_chosen_8")
        self.btn_chosen_9 = QtWidgets.QPushButton(self.deck_screen)
        self.btn_chosen_9.setEnabled(False)
        self.btn_chosen_9.setGeometry(QtCore.QRect(570, 630, 82, 112))
        self.btn_chosen_9.setStyleSheet("QPushButton:hover {\n"
"    border: 2px solid red;\n"
"    border-radius: 8px;\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    border: none;\n"
"}")
        self.btn_chosen_9.setText("")
        self.btn_chosen_9.setIconSize(QtCore.QSize(80, 110))
        self.btn_chosen_9.setFlat(True)
        self.btn_chosen_9.setObjectName("btn_chosen_9")
        self.btn_chosen_10 = QtWidgets.QPushButton(self.deck_screen)
        self.btn_chosen_10.setEnabled(False)
        self.btn_chosen_10.setGeometry(QtCore.QRect(670, 630, 82, 112))
        self.btn_chosen_10.setStyleSheet("QPushButton:hover {\n"
"    border: 2px solid red;\n"
"    border-radius: 8px;\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    border: none;\n"
"}")
        self.btn_chosen_10.setText("")
        self.btn_chosen_10.setIconSize(QtCore.QSize(80, 110))
        self.btn_chosen_10.setFlat(True)
        self.btn_chosen_10.setObjectName("btn_chosen_10")
        self.deck_screen_bg.raise_()
        self.btn_start_match.raise_()
        self.btn_deck_to_main.raise_()
        self.btn_card_plus_1.raise_()
        self.btn_card_plus_2.raise_()
        self.btn_card_plus_3.raise_()
        self.btn_card_plus_4.raise_()
        self.btn_card_plus_5.raise_()
        self.btn_card_plus_6.raise_()
        self.btn_card_minus_1.raise_()
        self.btn_card_minus_2.raise_()
        self.btn_card_minus_3.raise_()
        self.btn_card_minus_4.raise_()
        self.btn_card_minus_5.raise_()
        self.btn_card_minus_6.raise_()
        self.btn_card_dual_1.raise_()
        self.btn_card_dual_2.raise_()
        self.btn_card_dual_3.raise_()
        self.btn_card_dual_4.raise_()
        self.btn_card_dual_5.raise_()
        self.btn_card_dual_6.raise_()
        self.btn_randomize.raise_()
        self.btn_clear.raise_()
        self.btn_chosen_1.raise_()
        self.btn_chosen_2.raise_()
        self.btn_chosen_3.raise_()
        self.btn_chosen_4.raise_()
        self.btn_chosen_5.raise_()
        self.btn_chosen_6.raise_()
        self.btn_chosen_7.raise_()
        self.btn_chosen_8.raise_()
        self.btn_chosen_9.raise_()
        self.btn_chosen_10.raise_()
        self.stacked_widget.addWidget(self.deck_screen)
        self.game_screen = QtWidgets.QWidget()
        self.game_screen.setObjectName("game_screen")
        self.computer_hand_1 = QtWidgets.QLabel(self.game_screen)
        self.computer_hand_1.setGeometry(QtCore.QRect(590, 500, 82, 112))
        self.computer_hand_1.setStyleSheet("background-color: rgba(255, 255, 255, 0);")
        self.computer_hand_1.setText("")
        self.computer_hand_1.setScaledContents(False)
        self.computer_hand_1.setObjectName("computer_hand_1")
        self.computer_hand_2 = QtWidgets.QLabel(self.game_screen)
        self.computer_hand_2.setGeometry(QtCore.QRect(690, 500, 82, 112))
        self.computer_hand_2.setStyleSheet("background-color: rgba(255, 255, 255, 0);")
        self.computer_hand_2.setText("")
        self.computer_hand_2.setObjectName("computer_hand_2")
        self.computer_hand_3 = QtWidgets.QLabel(self.game_screen)
        self.computer_hand_3.setGeometry(QtCore.QRect(790, 500, 82, 112))
        self.computer_hand_3.setStyleSheet("background-color: rgba(255, 255, 255, 0);")
        self.computer_hand_3.setText("")
        self.computer_hand_3.setObjectName("computer_hand_3")
        self.computer_hand_4 = QtWidgets.QLabel(self.game_screen)
        self.computer_hand_4.setGeometry(QtCore.QRect(890, 500, 82, 112))
        self.computer_hand_4.setStyleSheet("background-color: rgba(255, 255, 255, 0);")
        self.computer_hand_4.setText("")
        self.computer_hand_4.setObjectName("computer_hand_4")
        self.btn_end_turn = QtWidgets.QPushButton(self.game_screen)
        self.btn_end_turn.setGeometry(QtCore.QRect(590, 640, 181, 41))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.btn_end_turn.setFont(font)
        self.btn_end_turn.setObjectName("btn_end_turn")
        self.btn_stand = QtWidgets.QPushButton(self.game_screen)
        self.btn_stand.setGeometry(QtCore.QRect(790, 640, 181, 41))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.btn_stand.setFont(font)
        self.btn_stand.setObjectName("btn_stand")
        self.btn_quit_match = QtWidgets.QPushButton(self.game_screen)
        self.btn_quit_match.setGeometry(QtCore.QRect(690, 710, 181, 41))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.btn_quit_match.setFont(font)
        self.btn_quit_match.setObjectName("btn_quit_match")
        self.player_set_1 = QtWidgets.QLabel(self.game_screen)
        self.player_set_1.setGeometry(QtCore.QRect(30, 80, 31, 31))
        self.player_set_1.setStyleSheet("background-color: rgba(255, 255, 255, 0);")
        self.player_set_1.setText("")
        self.player_set_1.setObjectName("player_set_1")
        self.player_total = QtWidgets.QLabel(self.game_screen)
        self.player_total.setGeometry(QtCore.QRect(340, 30, 41, 21))
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.player_total.setFont(font)
        self.player_total.setStyleSheet("background-color: rgba(255, 255, 255, 0);")
        self.player_total.setAlignment(QtCore.Qt.AlignCenter)
        self.player_total.setObjectName("player_total")
        self.computer_total = QtWidgets.QLabel(self.game_screen)
        self.computer_total.setGeometry(QtCore.QRect(640, 30, 41, 21))
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.computer_total.setFont(font)
        self.computer_total.setStyleSheet("background-color: rgba(255, 255, 255, 0);")
        self.computer_total.setAlignment(QtCore.Qt.AlignCenter)
        self.computer_total.setObjectName("computer_total")
        self.player_set_2 = QtWidgets.QLabel(self.game_screen)
        self.player_set_2.setGeometry(QtCore.QRect(30, 120, 31, 31))
        self.player_set_2.setStyleSheet("background-color: rgba(255, 255, 255, 0);")
        self.player_set_2.setText("")
        self.player_set_2.setObjectName("player_set_2")
        self.player_set_3 = QtWidgets.QLabel(self.game_screen)
        self.player_set_3.setGeometry(QtCore.QRect(30, 160, 31, 31))
        self.player_set_3.setStyleSheet("background-color: rgba(255, 255, 255, 0);")
        self.player_set_3.setText("")
        self.player_set_3.setObjectName("player_set_3")
        self.computer_set_1 = QtWidgets.QLabel(self.game_screen)
        self.computer_set_1.setGeometry(QtCore.QRect(960, 80, 31, 31))
        self.computer_set_1.setStyleSheet("background-color: rgba(255, 255, 255, 0);")
        self.computer_set_1.setText("")
        self.computer_set_1.setObjectName("computer_set_1")
        self.computer_set_2 = QtWidgets.QLabel(self.game_screen)
        self.computer_set_2.setEnabled(True)
        self.computer_set_2.setGeometry(QtCore.QRect(960, 120, 31, 31))
        self.computer_set_2.setStyleSheet("background-color: rgba(255, 255, 255, 0);")
        self.computer_set_2.setText("")
        self.computer_set_2.setObjectName("computer_set_2")
        self.computer_set_3 = QtWidgets.QLabel(self.game_screen)
        self.computer_set_3.setEnabled(True)
        self.computer_set_3.setGeometry(QtCore.QRect(960, 160, 31, 31))
        self.computer_set_3.setStyleSheet("background-color: rgba(255, 255, 255, 0);")
        self.computer_set_3.setText("")
        self.computer_set_3.setObjectName("computer_set_3")
        self.player_name = QtWidgets.QLabel(self.game_screen)
        self.player_name.setGeometry(QtCore.QRect(150, 30, 61, 21))
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.player_name.setFont(font)
        self.player_name.setStyleSheet("background-color: rgba(255, 255, 255, 0);")
        self.player_name.setAlignment(QtCore.Qt.AlignCenter)
        self.player_name.setObjectName("player_name")
        self.computer_name = QtWidgets.QLabel(self.game_screen)
        self.computer_name.setGeometry(QtCore.QRect(780, 30, 91, 21))
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.computer_name.setFont(font)
        self.computer_name.setStyleSheet("background-color: rgba(255, 255, 255, 0);")
        self.computer_name.setAlignment(QtCore.Qt.AlignCenter)
        self.computer_name.setObjectName("computer_name")
        self.player_turn = QtWidgets.QLabel(self.game_screen)
        self.player_turn.setGeometry(QtCore.QRect(100, 20, 41, 41))
        self.player_turn.setStyleSheet("background-color: rgba(255, 255, 255, 0);")
        self.player_turn.setText("")
        self.player_turn.setObjectName("player_turn")
        self.computer_turn = QtWidgets.QLabel(self.game_screen)
        self.computer_turn.setGeometry(QtCore.QRect(880, 20, 41, 41))
        self.computer_turn.setStyleSheet("background-color: rgba(255, 255, 255, 0);")
        self.computer_turn.setText("")
        self.computer_turn.setObjectName("computer_turn")
        self.player_hand_flip_1 = QtWidgets.QPushButton(self.game_screen)
        self.player_hand_flip_1.setEnabled(False)
        self.player_hand_flip_1.setGeometry(QtCore.QRect(75, 620, 32, 32))
        self.player_hand_flip_1.setStyleSheet("QPushButton:hover {\n"
"    border: 2px solid red;\n"
"    border-radius: 2px;\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    border: none;\n"
"}")
        self.player_hand_flip_1.setText("")
        self.player_hand_flip_1.setIconSize(QtCore.QSize(80, 110))
        self.player_hand_flip_1.setFlat(True)
        self.player_hand_flip_1.setObjectName("player_hand_flip_1")
        self.player_hand_flip_2 = QtWidgets.QPushButton(self.game_screen)
        self.player_hand_flip_2.setEnabled(False)
        self.player_hand_flip_2.setGeometry(QtCore.QRect(175, 620, 32, 32))
        self.player_hand_flip_2.setStyleSheet("QPushButton:hover {\n"
"    border: 2px solid red;\n"
"    border-radius: 2px;\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    border: none;\n"
"}")
        self.player_hand_flip_2.setText("")
        self.player_hand_flip_2.setIconSize(QtCore.QSize(80, 110))
        self.player_hand_flip_2.setFlat(True)
        self.player_hand_flip_2.setObjectName("player_hand_flip_2")
        self.player_hand_flip_3 = QtWidgets.QPushButton(self.game_screen)
        self.player_hand_flip_3.setEnabled(False)
        self.player_hand_flip_3.setGeometry(QtCore.QRect(275, 620, 32, 32))
        self.player_hand_flip_3.setStyleSheet("QPushButton:hover {\n"
"    border: 2px solid red;\n"
"    border-radius: 2px;\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    border: none;\n"
"}")
        self.player_hand_flip_3.setText("")
        self.player_hand_flip_3.setIconSize(QtCore.QSize(80, 110))
        self.player_hand_flip_3.setFlat(True)
        self.player_hand_flip_3.setObjectName("player_hand_flip_3")
        self.player_hand_flip_4 = QtWidgets.QPushButton(self.game_screen)
        self.player_hand_flip_4.setEnabled(False)
        self.player_hand_flip_4.setGeometry(QtCore.QRect(375, 620, 32, 32))
        self.player_hand_flip_4.setStyleSheet("QPushButton:hover {\n"
"    border: 2px solid red;\n"
"    border-radius: 2px;\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    border: none;\n"
"}")
        self.player_hand_flip_4.setText("")
        self.player_hand_flip_4.setIconSize(QtCore.QSize(80, 110))
        self.player_hand_flip_4.setFlat(True)
        self.player_hand_flip_4.setObjectName("player_hand_flip_4")
        self.player_hand_1 = QtWidgets.QPushButton(self.game_screen)
        self.player_hand_1.setEnabled(False)
        self.player_hand_1.setGeometry(QtCore.QRect(50, 500, 82, 112))
        self.player_hand_1.setStyleSheet("QPushButton:hover {\n"
"    border: 2px solid red;\n"
"    border-radius: 8px;\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    border: none;\n"
"}")
        self.player_hand_1.setText("")
        self.player_hand_1.setIconSize(QtCore.QSize(80, 110))
        self.player_hand_1.setFlat(True)
        self.player_hand_1.setObjectName("player_hand_1")
        self.player_hand_2 = QtWidgets.QPushButton(self.game_screen)
        self.player_hand_2.setEnabled(False)
        self.player_hand_2.setGeometry(QtCore.QRect(150, 500, 82, 112))
        self.player_hand_2.setStyleSheet("QPushButton:hover {\n"
"    border: 2px solid red;\n"
"    border-radius: 8px;\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    border: none;\n"
"}")
        self.player_hand_2.setText("")
        self.player_hand_2.setIconSize(QtCore.QSize(80, 110))
        self.player_hand_2.setFlat(True)
        self.player_hand_2.setObjectName("player_hand_2")
        self.player_hand_3 = QtWidgets.QPushButton(self.game_screen)
        self.player_hand_3.setEnabled(False)
        self.player_hand_3.setGeometry(QtCore.QRect(250, 500, 82, 112))
        self.player_hand_3.setStyleSheet("QPushButton:hover {\n"
"    border: 2px solid red;\n"
"    border-radius: 8px;\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    border: none;\n"
"}")
        self.player_hand_3.setText("")
        self.player_hand_3.setIconSize(QtCore.QSize(80, 110))
        self.player_hand_3.setFlat(True)
        self.player_hand_3.setObjectName("player_hand_3")
        self.player_hand_4 = QtWidgets.QPushButton(self.game_screen)
        self.player_hand_4.setEnabled(False)
        self.player_hand_4.setGeometry(QtCore.QRect(350, 500, 82, 112))
        self.player_hand_4.setStyleSheet("QPushButton:hover {\n"
"    border: 2px solid red;\n"
"    border-radius: 8px;\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    border: none;\n"
"}")
        self.player_hand_4.setText("")
        self.player_hand_4.setIconSize(QtCore.QSize(80, 110))
        self.player_hand_4.setFlat(True)
        self.player_hand_4.setObjectName("player_hand_4")
        self.help_flip_icon = QtWidgets.QLabel(self.game_screen)
        self.help_flip_icon.setGeometry(QtCore.QRect(20, 720, 32, 32))
        self.help_flip_icon.setStyleSheet("background-color: rgba(255, 255, 255, 0);")
        self.help_flip_icon.setText("")
        self.help_flip_icon.setPixmap(QtGui.QPixmap("assets/flip.png"))
        self.help_flip_icon.setObjectName("help_flip_icon")
        self.help_flip_text = QtWidgets.QLabel(self.game_screen)
        self.help_flip_text.setGeometry(QtCore.QRect(60, 720, 151, 31))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(False)
        font.setWeight(50)
        self.help_flip_text.setFont(font)
        self.help_flip_text.setStyleSheet("background-color: rgba(255, 255, 255, 0);")
        self.help_flip_text.setAlignment(QtCore.Qt.AlignCenter)
        self.help_flip_text.setObjectName("help_flip_text")
        self.player_slot_1 = QtWidgets.QLabel(self.game_screen)
        self.player_slot_1.setGeometry(QtCore.QRect(100, 80, 82, 112))
        self.player_slot_1.setStyleSheet("background-color: rgba(255, 255, 255, 0);")
        self.player_slot_1.setText("")
        self.player_slot_1.setObjectName("player_slot_1")
        self.player_slot_2 = QtWidgets.QLabel(self.game_screen)
        self.player_slot_2.setGeometry(QtCore.QRect(200, 80, 82, 112))
        self.player_slot_2.setStyleSheet("background-color: rgba(255, 255, 255, 0);")
        self.player_slot_2.setText("")
        self.player_slot_2.setObjectName("player_slot_2")
        self.player_slot_3 = QtWidgets.QLabel(self.game_screen)
        self.player_slot_3.setGeometry(QtCore.QRect(300, 80, 82, 112))
        self.player_slot_3.setStyleSheet("background-color: rgba(255, 255, 255, 0);")
        self.player_slot_3.setText("")
        self.player_slot_3.setObjectName("player_slot_3")
        self.player_slot_4 = QtWidgets.QLabel(self.game_screen)
        self.player_slot_4.setGeometry(QtCore.QRect(100, 210, 82, 112))
        self.player_slot_4.setStyleSheet("background-color: rgba(255, 255, 255, 0);")
        self.player_slot_4.setText("")
        self.player_slot_4.setObjectName("player_slot_4")
        self.player_slot_5 = QtWidgets.QLabel(self.game_screen)
        self.player_slot_5.setGeometry(QtCore.QRect(200, 210, 82, 112))
        self.player_slot_5.setStyleSheet("background-color: rgba(255, 255, 255, 0);")
        self.player_slot_5.setText("")
        self.player_slot_5.setObjectName("player_slot_5")
        self.player_slot_6 = QtWidgets.QLabel(self.game_screen)
        self.player_slot_6.setGeometry(QtCore.QRect(300, 210, 82, 112))
        self.player_slot_6.setStyleSheet("background-color: rgba(255, 255, 255, 0);")
        self.player_slot_6.setText("")
        self.player_slot_6.setObjectName("player_slot_6")
        self.player_slot_7 = QtWidgets.QLabel(self.game_screen)
        self.player_slot_7.setGeometry(QtCore.QRect(100, 340, 82, 112))
        self.player_slot_7.setStyleSheet("background-color: rgba(255, 255, 255, 0);")
        self.player_slot_7.setText("")
        self.player_slot_7.setObjectName("player_slot_7")
        self.player_slot_8 = QtWidgets.QLabel(self.game_screen)
        self.player_slot_8.setGeometry(QtCore.QRect(200, 340, 82, 112))
        self.player_slot_8.setStyleSheet("background-color: rgba(255, 255, 255, 0);")
        self.player_slot_8.setText("")
        self.player_slot_8.setObjectName("player_slot_8")
        self.player_slot_9 = QtWidgets.QLabel(self.game_screen)
        self.player_slot_9.setGeometry(QtCore.QRect(300, 340, 82, 112))
        self.player_slot_9.setStyleSheet("background-color: rgba(255, 255, 255, 0);")
        self.player_slot_9.setText("")
        self.player_slot_9.setObjectName("player_slot_9")
        self.computer_slot_1 = QtWidgets.QLabel(self.game_screen)
        self.computer_slot_1.setGeometry(QtCore.QRect(640, 80, 82, 112))
        self.computer_slot_1.setStyleSheet("background-color: rgba(255, 255, 255, 0);")
        self.computer_slot_1.setText("")
        self.computer_slot_1.setObjectName("computer_slot_1")
        self.computer_slot_2 = QtWidgets.QLabel(self.game_screen)
        self.computer_slot_2.setGeometry(QtCore.QRect(740, 80, 82, 112))
        self.computer_slot_2.setStyleSheet("background-color: rgba(255, 255, 255, 0);")
        self.computer_slot_2.setText("")
        self.computer_slot_2.setObjectName("computer_slot_2")
        self.computer_slot_3 = QtWidgets.QLabel(self.game_screen)
        self.computer_slot_3.setGeometry(QtCore.QRect(840, 80, 82, 112))
        self.computer_slot_3.setStyleSheet("background-color: rgba(255, 255, 255, 0);")
        self.computer_slot_3.setText("")
        self.computer_slot_3.setObjectName("computer_slot_3")
        self.computer_slot_4 = QtWidgets.QLabel(self.game_screen)
        self.computer_slot_4.setGeometry(QtCore.QRect(640, 210, 82, 112))
        self.computer_slot_4.setStyleSheet("background-color: rgba(255, 255, 255, 0);")
        self.computer_slot_4.setText("")
        self.computer_slot_4.setObjectName("computer_slot_4")
        self.computer_slot_5 = QtWidgets.QLabel(self.game_screen)
        self.computer_slot_5.setGeometry(QtCore.QRect(740, 210, 82, 112))
        self.computer_slot_5.setStyleSheet("background-color: rgba(255, 255, 255, 0);")
        self.computer_slot_5.setText("")
        self.computer_slot_5.setObjectName("computer_slot_5")
        self.computer_slot_6 = QtWidgets.QLabel(self.game_screen)
        self.computer_slot_6.setGeometry(QtCore.QRect(840, 210, 82, 112))
        self.computer_slot_6.setStyleSheet("background-color: rgba(255, 255, 255, 0);")
        self.computer_slot_6.setText("")
        self.computer_slot_6.setObjectName("computer_slot_6")
        self.computer_slot_7 = QtWidgets.QLabel(self.game_screen)
        self.computer_slot_7.setGeometry(QtCore.QRect(640, 340, 82, 112))
        self.computer_slot_7.setStyleSheet("background-color: rgba(255, 255, 255, 0);")
        self.computer_slot_7.setText("")
        self.computer_slot_7.setObjectName("computer_slot_7")
        self.computer_slot_8 = QtWidgets.QLabel(self.game_screen)
        self.computer_slot_8.setGeometry(QtCore.QRect(740, 340, 82, 112))
        self.computer_slot_8.setStyleSheet("background-color: rgba(255, 255, 255, 0);")
        self.computer_slot_8.setText("")
        self.computer_slot_8.setObjectName("computer_slot_8")
        self.computer_slot_9 = QtWidgets.QLabel(self.game_screen)
        self.computer_slot_9.setGeometry(QtCore.QRect(840, 340, 82, 112))
        self.computer_slot_9.setStyleSheet("background-color: rgba(255, 255, 255, 0);")
        self.computer_slot_9.setText("")
        self.computer_slot_9.setObjectName("computer_slot_9")
        self.game_screen_bg = QtWidgets.QLabel(self.game_screen)
        self.game_screen_bg.setGeometry(QtCore.QRect(0, 0, 1024, 768))
        self.game_screen_bg.setText("")
        self.game_screen_bg.setPixmap(QtGui.QPixmap("assets/bg_game_screen.png"))
        self.game_screen_bg.setObjectName("game_screen_bg")
        self.game_screen_bg.raise_()
        self.computer_hand_1.raise_()
        self.computer_hand_2.raise_()
        self.computer_hand_3.raise_()
        self.computer_hand_4.raise_()
        self.btn_end_turn.raise_()
        self.btn_stand.raise_()
        self.btn_quit_match.raise_()
        self.player_set_1.raise_()
        self.player_total.raise_()
        self.computer_total.raise_()
        self.player_set_2.raise_()
        self.player_set_3.raise_()
        self.computer_set_1.raise_()
        self.computer_set_2.raise_()
        self.computer_set_3.raise_()
        self.player_name.raise_()
        self.computer_name.raise_()
        self.player_turn.raise_()
        self.computer_turn.raise_()
        self.player_hand_flip_1.raise_()
        self.player_hand_flip_2.raise_()
        self.player_hand_flip_3.raise_()
        self.player_hand_flip_4.raise_()
        self.player_hand_1.raise_()
        self.player_hand_2.raise_()
        self.player_hand_3.raise_()
        self.player_hand_4.raise_()
        self.help_flip_icon.raise_()
        self.help_flip_text.raise_()
        self.player_slot_1.raise_()
        self.player_slot_2.raise_()
        self.player_slot_3.raise_()
        self.player_slot_4.raise_()
        self.player_slot_5.raise_()
        self.player_slot_6.raise_()
        self.player_slot_7.raise_()
        self.player_slot_8.raise_()
        self.player_slot_9.raise_()
        self.computer_slot_1.raise_()
        self.computer_slot_2.raise_()
        self.computer_slot_3.raise_()
        self.computer_slot_4.raise_()
        self.computer_slot_5.raise_()
        self.computer_slot_6.raise_()
        self.computer_slot_7.raise_()
        self.computer_slot_8.raise_()
        self.computer_slot_9.raise_()
        self.stacked_widget.addWidget(self.game_screen)
        self.stacked_widget.raise_()
        self.popup_set_status.raise_()
        self.popup_match_status.raise_()
        main_win.setCentralWidget(self.centralwidget)

        self.retranslateUi(main_win)
        self.stacked_widget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(main_win)

    def retranslateUi(self, main_win):
        _translate = QtCore.QCoreApplication.translate
        main_win.setWindowTitle(_translate("main_win", "Pazaak"))
        self.text_info_set.setText(_translate("main_win", "You lose the set."))
        self.btn_ok_set.setText(_translate("main_win", "OK"))
        self.text_info_match.setText(_translate("main_win", "You lose the match."))
        self.btn_ok_match.setText(_translate("main_win", "OK"))
        self.name_pazaak.setText(_translate("main_win", "Pazaak"))
        self.btn_play.setText(_translate("main_win", "play"))
        self.btn_help.setText(_translate("main_win", "instructions"))
        self.btn_quit_game.setText(_translate("main_win", "exit"))
        self.btn_help_to_main.setText(_translate("main_win", "BACK"))
        self.label.setText(_translate("main_win", "This screen will contain instructions on how to play the game."))
        self.btn_start_match.setText(_translate("main_win", "START MATCH"))
        self.btn_deck_to_main.setText(_translate("main_win", "BACK TO MENU"))
        self.btn_randomize.setText(_translate("main_win", "RANDOMIZE"))
        self.btn_clear.setText(_translate("main_win", "CLEAR"))
        self.btn_end_turn.setText(_translate("main_win", "END TURN"))
        self.btn_stand.setText(_translate("main_win", "STAND"))
        self.btn_quit_match.setText(_translate("main_win", "QUIT MATCH"))
        self.player_total.setText(_translate("main_win", "##"))
        self.computer_total.setText(_translate("main_win", "##"))
        self.player_name.setText(_translate("main_win", "Player"))
        self.computer_name.setText(_translate("main_win", "Computer"))
        self.help_flip_text.setText(_translate("main_win", "FLIP HAND CARD"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    main_win = QtWidgets.QMainWindow()
    ui = Ui_main_win()
    ui.setupUi(main_win)
    main_win.show()
    sys.exit(app.exec_())
